### ISSUE TITLE
Autoplay not working.

### ISSUE THREAD

**Issue by inverno4661** [inbasic/iyccenter#11]
installed= July 16/2014 @9:20 pm PST
so, i installed this, because youtube updated, so now every updated video is in a playlist which STILL PLAYS IN THE WRONG DIRECTION. ( who watches star wars in the order 6,5,4,3,2,1???) 
anyway, the auto video quality works, the pausing when loading the page works, it's the autoplay when the video ends that it broken. i am running Firefox 30, and i have checked that i have no other extensions/plugins that may be interfering with this extension.

i tried enabling LOOP, and adding 4000 seconds, in hope that that would stop it from auto loading, but it does not.
youtube trumps, and starts the next video.
i just don't know what to do.
help?

**Comment by inbasic** [comment]
Try the latest version and reopen if you are still experiencing these issues.
