### ISSUE TITLE
Option to disable AutoPlay playlist button

### ISSUE THREAD

**Issue by jez9999** [inbasic/iyccenter#15]
YouTube have decided to put in an incredibly annoying "AutoPlay" feature for playlists - when you start any video in a playlist, AutoPlay is highlighted and when the video finishes, the playlist will move on to the next video.  You can click on it to turn it off, but when you move away from the playlist and back again, it will be turned back on!  As far as I can tell there is no way to stop AutoPlay coming back on.  Please could you add a feature to keep AutoPlay off?

**Comment by dunealex** [comment]
I agree with  jez9999! It´s annoying as ****!
And the reason why I installed this add-on in the first place.

**Comment by inbasic** [comment]
There is a new method to disable auto-play next. Try the latest version and enable this option in the settings.
