### ISSUE TITLE
Youtube Center ignores the option "Don't load tabs until selected"

### ISSUE THREAD

**Issue by Manuela-Fereira** [inbasic/iyccenter#17]
All Youtube tabs are loaded on browser startup, regardless of the option "Don't load tabs until selected". This significantly slows down browser startup. (Fx 33.)

**Comment by inbasic** [comment]
Are you still experiencing this?

**Comment by Manuela-Fereira** [comment]
I'm using Fx47 x64 (Developer Edition) for now - Youtube Center doesn't work here, I even cannot open the settings.

**Comment by inbasic** [comment]
It is working on Nightly. Are you sure this is not a conflict with another extension? Please confirm by installing the extension on a clean profile; http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html

**Comment by Manuela-Fereira** [comment]
Oh, yes, it works on a clean profile. I'm sorry. And the issue seems to be gone
