### ISSUE TITLE
Just stopped working

### ISSUE THREAD

**Issue by psychonaut25** [inbasic/iyccenter#23]
I didn't do anything, change any settings, or any of that.  I was messing around with Fedora in VirtualBox- that's the only thing I was doing- when YouTube Control center simply stopped working.  I restarted my PC, and still had the same problem.  All I really want is to disable YouTube videos from automatically playing when the page loads.

I tried installing another Add-on called Flash control, and here's where it gets weird.  When I re-load the YouTube video, the little "flash control" icon appears in the middle of the video for a SPLIT SECOND (it's supposed to remain there, preventing the flash content from displaying, until you click on it) but then it vanishes and the video begins playing.

So, it seems like the problem is not with YouTube Control Center but with either YouTube itself, or with my computer.  But like I said, I didn't change anything!  I wasn't messing with Firefox, internet settings, or any of that when this happened.  It just happened on its own.

I'm using Win7 Pro x64 on a PowerSpec B332 desktop and running Pale Moon browser v25.2.1 (a fork of Firefox).  Everything is up-to-date & the latest version.

Update: ok, I also use NoScript, and I noticed "Googlevideo.com" wasn't allowed, so I allowed it. Now Flash Control seems to work...but I prefer YouTube Control Center. So I disabled Flash Control, tried again, and YouTube Control Center still isn't working.

So it seems the issue with Flash Control is entirely unrelated to the issue with YouTube Control.

Update 2: Automatic volume settings aren't working either.  However, the "hide toolbar" option is still functioning normally, as are a few other features.

Update 3: I have Lubuntu on my laptop so I tried on that, and everything works fine.  Clearly the problem is with my Windows machine, but as I said I didn't change anything so I've no idea what went wrong in Windows.  Perhaps one of my other add-ons updated itself and began to interfere.  If it'd help I can provide a list of all the other add-ons I'm using.

Update 4: I just loaded a video in a new tab and everything worked the way it's supposed to.  Then I refreshed the page and suddenly it was not working again.  Also, the only quality options I see on ANY video are 360p and 720p.

Update 5: Suddenly everything is working again.  All I did was restart the browser, instead this time instead of loading all the tabs of the old session (there were 549 of them) I only loaded some of them and exited the rest.  Previously when I tried restarting the PC and still had the problem, I had restarted the same session as before (in its entirety).  So I think it was just Pale Moon browser malfunctioning.

**Comment by psychonaut25** [comment]
Update: ok, I also use NoScript, and I noticed "Googlevideo.com" wasn't allowed, so I allowed it.  Now Flash Control seems to work...but I prefer YouTube Control Center.  So I disabled Flash Control, tried again, and YouTube Control Center still isn't working.

So it seems the issue with Flash Control is entirely unrelated to the issue with YouTube Control.

**Comment by psychonaut25** [comment]
Automatic volume settings aren't working either.  Nothing about this app is working right now.

**Comment by inbasic** [comment]
Please re-open if you are still having problem with the CC
