### ISSUE TITLE
Only partially working

### ISSUE THREAD

**Issue by dunealex** [inbasic/iyccenter#26]
I installed the plugin 2 days ago and it didn´t work.

A few things I tested:
-Pre-set quality doesn´t work for sure! 
-Playlist autoplay is still insisting on me to be enabled.
-Volume isn´t what I preset.
-Pre-load buffer isn´t loading.

Only thing working is the disabled autoplay when opening a video.

I run WIN7 Professional, and Firefox. Everything (including Flash and Java) are up-to-date.

**Comment by inbasic** [comment]
Try the latest version and reopen if you are still experiencing these issues.
