### ISSUE TITLE
Circumstances when preferences don't apply

### ISSUE THREAD

**Issue by JoshuaJSlone** [inbasic/iyccenter#27]
I have Autoplay and Autobuffer turned off. When left-clicking to normal video pages, this seems to work. However, if I open a YouTube link in a new tab, these are ignored--it will start playing automatically.

The rules also seem to have no effect on anything that isn't a standard YouTube video page. Videos embedded on pages will still autoplay, both on external sites and channel sites at YouTube.com itself.

**Comment by inbasic** [comment]
> I have Autoplay and Autobuffer turned off. When left-clicking to normal video pages, this seems to work. However, if I open a YouTube link in a new tab, these are ignored--it will start playing automatically.

Is this fixed on the latest built? https://github.com/inbasic/iyccenter/tree/master/src
Download the XPI file and drag & drop it into your firefox

> The rules also seem to have no effect on anything that isn't a standard YouTube video page. 

True, this is a performance consideration. Control Center does not inject anything to non-YouTube tabs.
