### ISSUE TITLE
Play button just loads new YouTube tab

### ISSUE THREAD

**Issue by IAmTakingThisUsername** [inbasic/iyccenter#28]
Not entirely sure if this counts an issue, but for me it's definitely a problem.  Whenever the addon's play button is pressed, a new tab opens into the YouTube homepage, regardless of whether or not a YouTube tab is already opened.  If I have video on pause, I would like for it to be actually played.

**Comment by inbasic** [comment]
Can you confirm this on a clean profile?
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles
