### ISSUE TITLE
Impressive with a few quirks

### ISSUE THREAD

**Issue by Zumofute** [inbasic/iyccenter#31]
Firefox version: 38.0.1

The extension build is solid, and it works very well. Here are a few quirks that I encountered while fiddling with the extension settings (all other settings work as expected):

--- Autobuffer video even if player is not playing ---
Does not work. I am guessing that this has to do with YouTube not permitting your extension to override the buffering rules set by YouTube. Of course, this rationale is understandable because the main goal is to increase efficiency and save bandwidth.

--- Display video views info pane ---
Works well when it is disabled and "Display action buttons pane" is enabled simultaneously. However, when the "Display action buttons pane" is disabled and "Display video views info pane" is enabled, the video views info pane does not appear.
It seems that "Display action buttons pane" overrides the "Display video views info pane" option even though the latter is enabled. Frankly, this does not concern me as I would keep them turned on, but I just wanted to point out the issue if you'd like to fix it.

Disabling the comments and related videos sections now creates a zen zero-distraction viewing experience. For that, I'd just like to show my appreciation and thank you very much for this great add-on.

**Comment by inbasic** [comment]
> --- Autobuffer video even if player is not playing ---

So if you set `[Player] Autoplays video when player loads` to false and `[Player] Autobuffer video even ..` to true, the video is buffering. Maybe not fully, but definitely partially. Right?

> --- Display video views info pane ---

Thanks for the report. It is now fixed on the latest built.
To try, download the XPI file here, 
https://github.com/inbasic/iyccenter/tree/master/src
and drag and drop it into your Firefox.

**Comment by Zumofute** [comment]
You're welcome. I confirm that all the above issues have been fixed in the new version.
Many thanks.
