### ISSUE TITLE
YouTube search bar (title bar)

### ISSUE THREAD

**Issue by GetsuYorokai** [inbasic/iyccenter#32]
Hi, I couldn't find a way to email you so I'm going to leave my suggestion here. Can you add an option to remove the search bar. Just a click and BOOM, its gone! Thank you!

**Comment by inbasic** [comment]
You mean just search bar itself or the entire header including account details, ...

**Comment by GetsuYorokai** [comment]
The whole header. it takes up tons of room. I'll use the search bar to seach youtube so I dont really need it. But the account stuff is kinda important. If you can move it to the side or something that would be cool, but otherwise just get rid of the whole thing. Thanks! 


     On Monday, June 15, 2015 12:34 AM, InBasic <notifications@github.com> wrote:
   

 You mean just search bar itself or the entire header including account details, ...—

**Comment by inbasic** [comment]
Well removing the search bar without removing the account section is not and requires hacking that might break UI if YouTube is updated. In the latest beta version, there is a new option to remove the whole search header,
https://github.com/inbasic/iyccenter/tree/master/src

Download the XPI file and drag & drop it into your Firefox. You need to go to options page and uncheck `[page] Display search bar`
