### ISSUE TITLE
Subtitle and watch later missing after Auto pause enabled

### ISSUE THREAD

**Issue by locxy** [inbasic/iyccenter#33]
![youtube](https://cloud.githubusercontent.com/assets/12731033/7960014/e4083cac-0a2f-11e5-9a00-eca722777726.JPG)

These icon will be disappeared as shown on picture. Is there a way to show them again without disable the addon or a way to disable the addon quickly temporary?

**Comment by inbasic** [comment]
What settings do I need to change to see this?

**Comment by locxy** [comment]
Hello there, 
Thanks for your reply, I'm not really sure why, I think need to find out why it is disappeared first right?

**Comment by inbasic** [comment]
Try the latest version. Go to the options page and reset all the settings back to the defaults. This should fix your problem.
