### ISSUE TITLE
Cinema Mode is faulty

### ISSUE THREAD

**Issue by Zumofute** [inbasic/iyccenter#34]
When video comments and suggestions panes are disabled, the "Cinema mode" button - just left of the "Full screen" button - behaves strangely when clicked in a sense that the video itself resizes, but the control panel of the video does not resize.

You may view this GIF showing "before and after" scenarios:
http://makeagif.com/jW_kn8

Alternatively, see the attached photos:
![image 1](https://cloud.githubusercontent.com/assets/5897049/8145259/478813aa-1233-11e5-88b0-e38fbe5308c4.png)
![image 2](https://cloud.githubusercontent.com/assets/5897049/8145258/475ec518-1233-11e5-990c-24ab6511a30e.png)

**Comment by billymcguffin** [comment]
I have experienced the same. Firefox version 38.0.5.

**Comment by inbasic** [comment]
This issue is fixed on the latest built,
To try download the XPI file from https://github.com/inbasic/iyccenter/tree/master/src then drag and drop it into your Firefox.

**Comment by Zumofute** [comment]
I installed the new version and confirm that it has been fixed. Thank you very much.
