### ISSUE TITLE
Buffering does not complete

### ISSUE THREAD

**Issue by gotquestions** [inbasic/iyccenter#36]
Thankyou for Youtube Control Center!

The buffering will not buffer to the end of the video. It only buffers halfway or so.
Can it be fixed to **buffer completely to the end** so that when I want to skip through to near the end
of the video I can do so quickly without having to wait for buffering at the end.
Example below. Thankyou.
![youtube center control progressbar](https://cloud.githubusercontent.com/assets/8550969/8198550/2b001fa8-145d-11e5-9315-a1b9042e1030.PNG)

**Comment by inbasic** [comment]
Not anyway I am aware of. YouTube player only buffers a portion of videos such that there would be no waiting during the play. If you know any other script can do full buffering let me know.

**Comment by inbasic** [comment]
http://firefox.add0n.com/no-dash-playback.html might be of your interest.
