### ISSUE TITLE
Show video controls on player not appear on Fullscreen

### ISSUE THREAD

**Issue by gotquestions** [inbasic/iyccenter#39]
I have "Show video controls on player" checked and the video controls appear in Normal Mode, and Theater Mode, but not in Fullscreen and I would like it in fullscreen ALSO.
So if others usually don't want it to show in Fullscreen then could you please add a second Option for Fullscreen?
"Show video controls on player for Normal and Theater Mode"
"Show video controls on player in FullScreen Mode"
Thankyou

NOTE: Something handy you might be interested in for your own use:
Github Comment Enhancer
Adds Markup Tag Bar for github.com
https://greasyfork.org/en/scripts/493-github-comment-enhancer
With Greasemonkey Addon https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/

![github markup bar bbcode tags](https://cloud.githubusercontent.com/assets/8550969/8270302/163e2d92-178e-11e5-8d54-bcca111ff97f.PNG)

**Comment by inbasic** [comment]
Well, I am not sure if it is possible,
https://developers.google.com/youtube/player_parameters#controls

There is no such an option in the documentation.

**Comment by gotquestions** [comment]
This script https://greasyfork.org/en/scripts/3435-youtube-embed-tweak/code
With Greasemonkey Addon. https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/

 Must go into code and set this section to 0
// Set autohide = 0 or 1, 1 enables auto hide of player controls. (0 is default behaviour)
var autohide = 0;

Go to either of these pages and scroll down to find a YOUTUBE video with FullScreen Button.
The control panel will remain visible in FullScreen mode if paused or PLAYING.
https://twitter.com/search?q=musicvideo&vertical=default&f=tweets
https://twitter.com/search?q=video&vertical=default&f=tweets

Youtube pages are excluded in the Script. It is only for embedded Youtube videos.

**Comment by inbasic** [comment]
Thanks for the suggestion. There is a new option available on the latest beta version to have control over full-screen video controls
https://github.com/inbasic/iyccenter/blob/master/src/iyccenter.xpi?raw=true

**Comment by gotquestions** [comment]
Yes ! Youtube videos Control Panel appears in Fullscreen mode although one time it didn't so I don't really know why ( I had checkmarked the option) but will observe more.
It doesn't work for embedded videos though.
**Thankyou** very much for adding that option for me!
