### ISSUE TITLE
Video is black after 6/22 update

### ISSUE THREAD

**Issue by paschott** [inbasic/iyccenter#40]
It was working great before that update, but the videos are just a black screen now if the add-on is enabled in Firefox 38.0.5 on Win 8.1. If I disable the add-on, I can watch videos. All other aspects seem to work and I can even hear audio and see the preview thumbnails when hovering over the timeline. I just can't actually see the video.

**Comment by inbasic** [comment]
Please check the extension on a clean profile first to make sure this is not a conflict with another extension,
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles
