### ISSUE TITLE
Youtube search bar vanishes when YCC is active.

### ISSUE THREAD

**Issue by chromeisstupid** [inbasic/iyccenter#43]
As stated in the title, when I turn YCC on, Youtube search bar goes missing, and the rest of the page is pulled up. Turning YCC off solves the issue. Additionally, some YCC options don't have their descriptions, so it's impossible to tell what you're turning on/off. Anyone having the same problem? Hope someone can help, thank you.

**Comment by inbasic** [comment]
Get the latest release and go to the options page. Reset all settings back to defaults. This should fix the problem.
