### ISSUE TITLE
Add a way to disable "default" video playback volume

### ISSUE THREAD

**Issue by zonthori** [inbasic/iyccenter#44]
If I change the volume for one video, I want it to stay for the next video. This has caused me to NOT use this add on.

P.S Sorry about the title, I was pretty tired when making this post.

**Comment by inbasic** [comment]
Go to the options page and define a default volume for the player.

**Comment by zonthori** [comment]
I don't think you are getting what I am saying. I don't want a default. I want what I select on one video to stay for the next, so in one video if I up it a bit, it should stay for the next video. If I pull it down, it should be down in the next video too. I am not going to set a default volume every time I want it to change. Not using this. Youtube by itself is fine.
