### ISSUE TITLE
firefox add-on not downloading/installing

### ISSUE THREAD

**Issue by minipower50** [inbasic/iyccenter#48]
The firefox addon is not downloading for me. I get the message "downloading add-on" But nothing happens.
If I open the download utton into a seperate tab, I get a message "firefox has blocked this add-on" with a allow button. Of course I tried pressing the allow button, but still not downloading/installing.
This is mobile firefox "android" CM10.1 android 4.2.2

**Comment by minipower50** [comment]
sorry for my tard moment of fogeting to tell this is mobile firefox "android"

**Comment by minipower50** [comment]
I downloaded to tablet from git and used file browser and told it to open using firefox. It still did not install. I have firefox up to date with v41.0

**Comment by inbasic** [comment]
@minipower50 is extension is only for Firefox desktop. The UI cannot be used in the Android version and hence the extension cannot initiate.

**Comment by minipower50** [comment]
Big DEERP  on my part.  It's a bummer, it is unable to work on Android. I have not been able to find an youtube add-on that will install on my android tablet.

**Comment by DoraLorraine** [comment]
---- InBasic <notifications@github.com> wrote: 
> @minipower50 is extension is only for Firefox desktop. The UI cannot be used in the Android version and hence the extension cannot initiate.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/inbasic/iyccenter/issues/48#issuecomment-146089761


Thank You.  Sorry it took so long to reply.  I do appreciate your time.

Dora

**Comment by DoraLorraine** [comment]
---- minipower50 <notifications@github.com> wrote: 
> Big DEERP  on my part.  It's a bummer, it is unable to work on Android. I have not been able to find an youtube add-on that will install on my android tablet.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/inbasic/iyccenter/issues/48#issuecomment-147779158


Thank You.  Sorry it took so long to reply I do appreciate your time.

Dora
