### ISSUE TITLE
Spelling mistake in addon preferences [UI] Middle click on...

### ISSUE THREAD

**Issue by fiver22** [inbasic/iyccenter#49]
"[UI] Middle click on the toolbar button: Default (do noting)" contains spelling error on the last full word in the default choice. 'noting' should be replaced with 'nothing'.

May not have shown in spell check as 'noting' is a common english word meaning *"to write or mark down briefly; make a memorandum of:"* **(1)**
Whereas 'nothing' is defined as *"no thing; not anything; naught:"* **(2)**

**(1)**Dictionary.com, "noting," in The American Heritage® Dictionary of Idioms by Christine Ammer. Source location: Houghton Mifflin Company. http://dictionary.reference.com/browse/noting. Available: http://dictionary.reference.com. Accessed: October 28, 2015.
**(2)**Dictionary.com, "nothing," in Dictionary.com Unabridged. Source location: Random House, Inc. http://dictionary.reference.com/browse/nothing. Available: http://dictionary.reference.com. Accessed: October 28, 2015.

**Comment by inbasic** [comment]
Thanks for the report. It is fixed on the latest release
