### ISSUE TITLE
Removing add-on

### ISSUE THREAD

**Issue by Alan-E** [inbasic/iyccenter#51]
I installed this add-on and now none of the YouTube videos will work. Cannot make any of them play at all. I removed this add-on and YouTube is still broken. Does it leave bits behind that have to manually removed in about:config?

**Comment by inbasic** [comment]
Nope. You can just do one restart just in case (although it is not necessary)

>  Cannot make any of them play at all. 

As far as I know this extension is not interfering with YouTube player at all! Are you sure this has been caused by CC?

**Comment by Alan-E** [comment]
Yes everything was 'fine' with youtube this morning. Having YouTube autoplay is annoying and one of the reasons I installed this add-on. After removing this add-on and not having YouTube work, I did a complete reset of Firefox and it still is not working. I'll have to uninstall FF and reload it. Not a big deal.

**Comment by inbasic** [comment]
If you have reset your Firefox definitely the problem can not be caused by CC. Anyhow instead of reinstalling FF, you can switch to a clean profile as well,
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by Alan-E** [comment]
Thank you for responding. :-) I am using Windows 10. Apparently I needed to reboot the computer to clear whatever it was that was causing the issue. You're probably correct in that it may not have been the CC add-on.
