### ISSUE TITLE
e10s compatibility

### ISSUE THREAD

**Issue by phils** [inbasic/iyccenter#55]
This addon doesn't work with e10s (multi-process) enabled in Firefox.. it is already on in nightlies and will be in the next beta most likely (it was almost enabled in the current beta but pulled at last minute).

So this addon will cease to function at all in firefox in the coming months.

More info here: https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox

**Comment by inbasic** [comment]
[0.3.6b1](https://github.com/inbasic/iyccenter/blob/master/builds/jid1-CikLKKPVkw6ipw@jetpack-0.3.6b1.xpi?raw=true) works pretty fine in e10s. The only known issue is it cannot detect players until YouTube pages are fully loaded.

Let me know if you have another problem with it. Please try the extension on a clean profile to report bugs; http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html
