### ISSUE TITLE
Unresponsive browser when opening youtube after Fx 48

### ISSUE THREAD

**Issue by ekaris** [inbasic/iyccenter#59]
After the update to version 48 I can no longer use youtube with this extension enabled

**Comment by inbasic** [comment]
Thanks for the report. This is fixed on 0.3.6
https://addons.mozilla.org/en-US/firefox/addon/youtube-control-center/versions/

**Comment by ekaris** [comment]
Fixed but I still get occasional crashes still when viewing youtube videos in full screen and 1080p
Not sure if is the extension

**Comment by inbasic** [comment]
Please reopen if you are confident crashes are due to this add-on. It is recommended to try the extension on a clean profile to make sure there is no conflicts with another add-on of yours; http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html
