### ISSUE TITLE
Add option to not show update page

### ISSUE THREAD

**Issue by ekaris** [inbasic/iyccenter#60]
Add option to to not show the update page on next restart

**Comment by inbasic** [comment]
Can you confirm this on a clean profile? Seems like the extension cannot store its preference. http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html


To debug the current profile please follow:
1. Open the Error Console (Ctrl + Shift + J)
2. Disable and re-enable the extension
3. Have you got a new error message in the console?

**Comment by ekaris** [comment]
But the extension doesn't have an option to disable the update page.
I get this on my current profile:
Could not read chrome manifest 'file:///usr/lib/firefox/chrome.manifest'.
Warning: attempting to write 5235 bytes to preference extensions.bootstrappedAddons. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Warning: attempting to write 5466 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Warning: attempting to write 5494 bytes to preference extensions.bootstrappedAddons. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Warning: attempting to write 5465 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
unreachable code after return statement[Saber mais]main.js:1111:6

**Comment by inbasic** [comment]
> But the extension doesn't have an option to disable the update page.

Right. I must have forgotten to add this option. Will have this on the next release.

None of these warnings seems to be relevant to the reported issue. Must be a profile damage case.
