### ISSUE TITLE
Display options not working

### ISSUE THREAD

**Issue by vsauder** [inbasic/iyccenter#68]
The toolbar is working great, but for some reason, it's not hiding comments, recommended videos, etc., when I have those features disabled. I've tried restarting the browser, refreshing the tab, but it's not working. Could you please help?

Thanks so much! I look forward to your reply.

**Comment by rexland** [comment]
it's broke, they changed it and removed your ability to do many, many things

**Comment by inbasic** [comment]
@vsauder are you sure it is not caused by another extension? What is your browser version?
