### ISSUE TITLE
you really messed up with new update

### ISSUE THREAD

**Issue by rexland** [inbasic/iyccenter#72]
yes, I've disabled this add on.  your new update removes all the controls I enjoyed before with some crappy short list that's a pain in the a** to use.  As of Aug 28, it's now disabled.  Why did you destroy something that was so good before?  Dumb if you ask me.  Maybe youtube bought you out and made you stop?  I'm sure I won't be the last as more people start to view vids and find they aren't working like before and then take forever to find out how to maybe change some settings but realize they can't and get so pissed off they sign up for github when they have no reason just to tell you that you F****d up.  maybe you'll get it eventually.

**Comment by inbasic** [comment]
I am getting tired of comments like this.

1. You can switch back to the old version if you are not planing to move to FF57
2. You can request feature enhancement if there is anything important is missing on the new WebEx port
3. Mozilla is forcing WebEx so there was no way to keep the old version.
