### ISSUE TITLE
Cannot click addon icon to get options

### ISSUE THREAD

**Issue by braille8011** [inbasic/iyccenter#73]
When I click the addon icon on the toolbar, it opens a new tab for youtube.com instead of the addon options.

**Comment by VigorMortis** [comment]
I imagine he'll want to know your operating system, browser version, etc. 

Good luck even getting a response. Really: 'best wishes!

**Comment by inbasic** [comment]
Se when there is no open YouTube player, the toolbar button opens a new YouTube tab. When there is a player, it will display the popup.

**Comment by braille8011** [comment]
Yeah... looks like user error in this case. The addon works as intended, as described by inbasic. Sorry to trouble you all.
