### ISSUE TITLE
[Question] Logs/History

### ISSUE THREAD

**Issue by RandomGOTI** [inbasic/iyccenter#74]
Will this feature be brought back to the webex port if possible ? the possibility of having a easy access history to my recent viewed youtube links was the reason i started using ytcc over the others
Thanks in advance

**Comment by inbasic** [comment]
Yes, version 0.5.3 has new synced history with YouTube. Thanks for the report.

**Comment by RandomGOTI** [comment]
My question was slightly misunderstood, what i meant was the local history/logs of watched youtube videos 
(profiledir/youtube-control-center/storage.sqlite) from the last legacy version 0.4.3

I am on 55.0.3 (64-bit) and sadly the entries from the history aren't clickable anymore 
So i will reopen this as suggestion / feature request:
I've tested the 0.5.3 and everything works fine though i am not always logged on a youtube account and the synched history is not as useful for some as  the local from the legacy may be and so how about adding a button next to the synched one for local history that would use storage.sqlite as before ?
Sorry for the poorly report
