### ISSUE TITLE
Extension design

### ISSUE THREAD

**Issue by roose** [inbasic/iyccenter#79]
Hey @inbasic, I created new design for that extension, are you interested to implement it?
![ffycc](https://user-images.githubusercontent.com/277651/37454273-535617d2-2864-11e8-8f9d-bb9b4423a6d3.png)
![gif](https://user-images.githubusercontent.com/277651/37454355-87e0588c-2864-11e8-9c33-1122209bc16d.gif)

**Comment by inbasic** [comment]
This looks great! We have it on 0.6.0. Please take a look and push commits if there are fine tunes.

**Comment by roose** [comment]
@inbasic beautiful! Many thanks!
Design in figma, if need: https://www.figma.com/file/eqtTXXDwW89vl3xs1sW0vaSU/YouTube-Control-Center

**Comment by inbasic** [comment]
Thanks @roose.
