### ISSUE TITLE
Visual bugs on new design

### ISSUE THREAD

**Issue by roose** [inbasic/iyccenter#80]
If image is have big height:
![ycc01](https://user-images.githubusercontent.com/277651/38983531-625086d0-43e6-11e8-868f-6018ee858175.jpg)

May be fix it as in this pen: https://codepen.io/roose/pen/ermBwy ?
220px look nice for most clips.

**Comment by inbasic** [comment]
Thanks it is fixed on 0.6.3

**Comment by roose** [comment]
Thank you very much!
